'use client'
import Head from 'next/head'
import CustomTextField from 'src/components/text-field'
import { Box } from '@mui/material'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'
import { ReactNode } from 'react'

export default function Home() {


  return (
    <>
      <Head>
        <title>Shop-App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* <Button variant='contained'>Hello world</Button> */}
      <Box sx={{margin:6 , width:"200px"}}>
        {' '}
        <CustomTextField id='outlined-multiline-flexible' label='Multiline'>
          Hello word update
        </CustomTextField>
      </Box>
    </>
  )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
